ARG OPENJDK_VERSION=11
ARG DEBIAN_RELEASE=""
FROM openjdk:${OPENJDK_VERSION}-jre-slim${DEBIAN_RELEASE}
ARG TARGETPLATFORM
ARG TARGETARCH
ARG TARGETVARIANT
ARG PYTHON_VERSION=3.8.8
ARG SPARK_VERSION=3.2.0
ARG SPARK_EXTRAS=

LABEL org.opencontainers.image.title="Apache PySpark $SPARK_VERSION" \
      org.opencontainers.image.version=$SPARK_VERSION

ENV PATH="/opt/miniconda3/bin:${PATH}"
ENV PYSPARK_PYTHON="/opt/miniconda3/bin/python"

RUN set -ex && \
	apt-get update && \
    apt-get install -y curl bzip2 --no-install-recommends && \
    if [ "${TARGETARCH}" = "arm64" ]; then curl -s -L --url "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-aarch64.sh" --output /tmp/miniconda.sh; else curl -s -L --url "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" --output /tmp/miniconda.sh; fi && \
    bash /tmp/miniconda.sh -b -f -p "/opt/miniconda3" && \
    rm /tmp/miniconda.sh && \
    conda config --set auto_update_conda true && \
    conda config --set channel_priority false && \
    conda update conda -y --force-reinstall && \
    conda install pip && \
    conda install -y python=${PYTHON_VERSION} && \
    conda clean -tipy && \
    echo "PATH=/opt/miniconda3/bin:\${PATH}" > /etc/profile.d/miniconda.sh && \
    pip install --no-cache pyspark[$SPARK_EXTRAS]==${SPARK_VERSION} && \
    SPARK_HOME=$(python /opt/miniconda3/bin/find_spark_home.py) && \
    echo "export SPARK_HOME=$(python /opt/miniconda3/bin/find_spark_home.py)" > /etc/profile.d/spark.sh && \
    curl -s -L --url "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar" --output $SPARK_HOME/jars/aws-java-sdk-bundle-1.11.901.jar && \
    curl -s -L --url "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar" --output $SPARK_HOME/jars/hadoop-aws-3.3.1.jar && \
    mkdir -p $SPARK_HOME/conf && \
    echo "spark.hadoop.fs.s3.impl=org.apache.hadoop.fs.s3a.S3AFileSystem" >> $SPARK_HOME/conf/spark-defaults.conf && \
    echo "spark.hadoop.fs.s3a.fast.upload.buffer=bytebuffer" >> $SPARK_HOME/conf/spark-defaults.conf && \
    apt-get remove -y curl bzip2 && \
    apt-get autoremove -y && \
    apt-get clean



WORKDIR /job

COPY requirements.txt requirements.txt
RUN conda init

RUN pip install -r requirements.txt

COPY budgetguard/ budgetguard/

COPY .env budgetguard/.env

ENV PATH="${SPARK_HOME}/bin:${PATH}"

ENTRYPOINT ["spark-submit"]
CMD ["--help"]
