name: Build develop branch CI/CD

on:
  push:
    branches:
      - 'develop'


env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PAT: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            token: ${{ env.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry and testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions poetry

      - name: Run tox
        run: tox
  
      - name: Get current version from VERSION file
        run: |
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
          VERSION=${{ env.VERSION }}
          VERSION=$(bump2version --list patch --dry-run --allow-dirty | awk -F= '/new_version=/ { print $2 }')
          echo $VERSION
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
  
      - name: Bump code version (patch)
        uses: FragileTech/bump-version@main
        with:
            current_version: "${{ env.VERSION }}"
            files: [VERSION, pyproject.toml]
            commit_name: "GithubActionsBot -> Version bump (CI/CD)"
            commit_email: "actions@github.com"
            login: "GitHubActionsBot"
            token: "${{ secrets.PAT }}"
            part: patch
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ env.VERSION }}
            release_name: Release v${{ env.VERSION }}
            draft: false
            prerelease: false
          
