name: Build develop branch CI/CD

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install poetry

      - name: Run tox
        run: tox
    
      - name: Install bump2version
        run: pip install bump2version
  
      - name: Bump version
        run: |
          # Bump version in pyproject.toml
          bump2version patch pyproject.toml
          # Bump version in __init__.py
          bump2version patch package/__init__.py
  
      - name: Commit version bump
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m "Bump version [skip ci]"
          git push
