name: Build develop branch CI/CD

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
          python -m pip install poetry
          python -m pip install bump2version

      - name: Run tox
        run: tox
  
      - name: Bump version
        run: bump2version patch
    
      - name: Read version number
        run: |
          echo "::set-env name=VERSION::$(cat VERSION)"
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ env.VERSION }}
            release_name: Release v${{ env.VERSION }}
            draft: false
            prerelease: false
          
