name: Develop branch CI/CD

on:
  push:
    branches:
      - "develop"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build develop branch
    if: ${{ !contains(github.event.head_commit.message, '✅ Bump version from') }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2 tox tox-gh-actions

      - name: Run tox
        run: tox

  release:
    runs-on: ubuntu-latest
    name: Create release
    if: ${{ !contains(github.event.head_commit.message, '✅ Bump version from') }}
    needs: build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ env.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry and bump2version
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2 bump2version

      - name: Get current version and new version from VERSION file
        run: |
          RAW_OUTPUT=$(bumpversion --list patch --dry-run)
          echo "$RAW_OUTPUT"
          OLD_VERSION=$(echo "$RAW_OUTPUT" | grep -o 'current_version=\S*' | cut -d= -f2)
          NEW_VERSION=$(echo "$RAW_OUTPUT" | grep -o 'new_version=\S*' | cut -d= -f2)
          echo "Current Version: $OLD_VERSION"
          echo "New Version: $NEW_VERSION"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
          echo "OLD_VERSION=${OLD_VERSION}" >> $GITHUB_ENV

      - name: Bump version
        run: |
          bump2version patch --allow-dirty --new-version ${{ env.NEW_VERSION }} --verbose

      - name: Update requirements.txt for release
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Commit version bump
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -a -m "✅ Bump version from ${{ env.OLD_VERSION }} to ${{ env.NEW_VERSION }} by Github Actions Bot 🤖"

      - name: Push changes to protected branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          branch: develop

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEW_VERSION }}
          release_name: Release v${{ env.NEW_VERSION }}
          draft: false
          prerelease: false

  publish:
    runs-on: ubuntu-latest
    name: Publish package
    if: ${{ !contains(github.event.head_commit.message, '✅ Bump version from') }}
    needs: release
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.4.2
      - name: Configure poetry
        env:
          pypi_token: ${{ secrets.PyPI_TOKEN }}
        run: poetry config pypi-token.pypi $pypi_token

      - name: Publish poetry package
        run: poetry publish --build

      - name: Sleep for 2 minutes (waiting for PyPI to update)
        uses: jakejarvis/wait-action@master
        with:
          time: "120s"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push general image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: budget-guard
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-${{ env.NEW_VERSION }} --build-arg VERSION=${{ env.NEW_VERSION }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-${{ env.NEW_VERSION }}

      - name: Build, tag, and push EMR image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: budget-guard-emr
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-${{ env.NEW_VERSION }} --build-arg VERSION=${{ env.NEW_VERSION }} -f Dockerfile_emr .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-${{ env.NEW_VERSION }}

      - name: Upload emr_main.py to S3 bucket
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket: budget-guard-main
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region us-east-1
          aws s3 cp ./budgetguard/emr_main.py s3://$aws_s3_bucket/
