name: Feature branch CI/CD

on:
  push:
    branches:
      - "feature**"

jobs:
  build:
    name: Build feature branch CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions bump2version

      - name: Run tox
        run: tox
      
      - name: Get current version and new version from VERSION file
        run: |
          RAW_OUTPUT=$(bumpversion --list patch --dry-run)
          echo "$RAW_OUTPUT"
