name: Build feature branch CI/CD

on:
  push:
    branches:
      - 'feature**'

jobs:
  build:
    name: Build feature branch CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox
      
      - name: Upload AWS MWAA requirements to S3 bucket
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-bucket: "budgetguard-mwaa-bucket"
          file-path: './requirements-mwaa.txt'
          destination-dir: "/"
          bucket-root: "/"

      - name: Upload AWS MWAA DAGs to S3 bucket
        uses: ochanje210/s3-upload-action@master
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_S3_BUCKET: "budgetguard-mwaa-bucket"
          SOURCE_DIR: './budgetguard/budgetguard/dags'
          DEST_DIR: 'dags'
