name: Build production branch CI/CD

on:
  push:
    branches:
        - "production"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PAT: ${{ secrets.PAT }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '✅ Bump version from') }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            token: ${{ env.PAT }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install poetry and testing dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions poetry bump2version

      - name: Run tox
        run: tox
  
      - name: Get current version and new version from VERSION file
        run: |
            RAW_OUTPUT=$(bumpversion --list minor --dry-run)
            OLD_VERSION=$(echo "$RAW_OUTPUT" | grep -o 'current_version=\S*' | cut -d= -f2)
            NEW_VERSION=$(echo "$RAW_OUTPUT" | grep -o 'new_version=\S*' | cut -d= -f2)
            echo "Current Version: $OLD_VERSION"
            echo "New Version: $NEW_VERSION"
            echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
            echo "OLD_VERSION=${OLD_VERSION}" >> $GITHUB_ENV

      - name: Bump version in pyproject.toml
        run: |
            bump2version minor --allow-dirty --new-version ${{ env.NEW_VERSION }} --verbose
      
      - name: Commit version bump
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            git commit -a -m "✅ Bump version from ${{ env.OLD_VERSION }} to ${{ env.NEW_VERSION }} by Github Actions Bot 🤖"

      - name: Push changes to protected branch
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ env.GITHUB_TOKEN }}
            branch: production

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            tags: true
    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ env.NEW_VERSION }}
            release_name: Release v${{ env.NEW_VERSION }}
            draft: false
            prerelease: false

      - name: Configure poetry
        env:
          pypi_token: ${{ secrets.PyPI_TOKEN }}
        run: poetry config pypi-token.pypi $pypi_token
    
      - name: Build and publish
        run: poetry publish --build
